# Tomcat
server:
    port: 8002
#spring
spring:
    application:
        name: provide-payment
    datasource:
         # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/cloud2021?allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF8
        username: root
        password: root



mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.zw.cloud.entity
eureka:
  client:
  #是否将自己注测到eureka里面
    register-with-eureka: true
    #是否从eureka服务端抓取已有的注册信息
    fetch-registry: true
    service-url:
    #配置集群
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://localhost:7001/eureka,http://127.0.0.1:7002/eureka/
      #显示名称和ip
  instance:
    instance-id: payment8002
    prefer-ip-address: true