server:
    port: 9991

spring:
    application:
        name: gateway-cloud
    cloud:
        gateway:
          discovery:
              locator:
                enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由
          routes:
            - id: payment_route
              uri: lb://PROVIDE-PAYMENT
              predicates:
                   - Path=/pay/get/**

            - id: payment_route2
              uri: lb://PROVIDE-PAYMENT
              predicates:
                    - Path=/payment/lb/**
eureka:
  client:
  #是否将自己注测到eureka里面
    register-with-eureka: true
    #是否从eureka服务端抓取已有的注册信息
    fetch-registry: true
    service-url:
    #配置集群
      defaultZone: http://localhost:7001/eureka
      #defaultZone: http://localhost:7001/eureka,http://127.0.0.1:7002/eureka/